# CMake generated Testfile for 
# Source directory: D:/Projects/Develop/Tools/Lighters
# Build directory: D:/Projects/Develop/Tools/Lighters/build-maya2023
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(lightsurgeon_unit "D:/Projects/Develop/Tools/Lighters/build-maya2023/Debug/lightsurgeon_tests.exe")
  set_tests_properties(lightsurgeon_unit PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;36;add_test;D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(lightsurgeon_unit "D:/Projects/Develop/Tools/Lighters/build-maya2023/Release/lightsurgeon_tests.exe")
  set_tests_properties(lightsurgeon_unit PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;36;add_test;D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(lightsurgeon_unit "D:/Projects/Develop/Tools/Lighters/build-maya2023/MinSizeRel/lightsurgeon_tests.exe")
  set_tests_properties(lightsurgeon_unit PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;36;add_test;D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(lightsurgeon_unit "D:/Projects/Develop/Tools/Lighters/build-maya2023/RelWithDebInfo/lightsurgeon_tests.exe")
  set_tests_properties(lightsurgeon_unit PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;36;add_test;D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;0;")
else()
  add_test(lightsurgeon_unit NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(lightsurgeon_cli_analyze "D:/Projects/Develop/Tools/Lighters/build-maya2023/Debug/lightsurgeon.exe" "analyze" "D:/Projects/Develop/Tools/Lighters/tests/fixtures/studio.json")
  set_tests_properties(lightsurgeon_cli_analyze PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;37;add_test;D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(lightsurgeon_cli_analyze "D:/Projects/Develop/Tools/Lighters/build-maya2023/Release/lightsurgeon.exe" "analyze" "D:/Projects/Develop/Tools/Lighters/tests/fixtures/studio.json")
  set_tests_properties(lightsurgeon_cli_analyze PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;37;add_test;D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(lightsurgeon_cli_analyze "D:/Projects/Develop/Tools/Lighters/build-maya2023/MinSizeRel/lightsurgeon.exe" "analyze" "D:/Projects/Develop/Tools/Lighters/tests/fixtures/studio.json")
  set_tests_properties(lightsurgeon_cli_analyze PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;37;add_test;D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(lightsurgeon_cli_analyze "D:/Projects/Develop/Tools/Lighters/build-maya2023/RelWithDebInfo/lightsurgeon.exe" "analyze" "D:/Projects/Develop/Tools/Lighters/tests/fixtures/studio.json")
  set_tests_properties(lightsurgeon_cli_analyze PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;37;add_test;D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;0;")
else()
  add_test(lightsurgeon_cli_analyze NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(lightsurgeon_cli_pixel "D:/Projects/Develop/Tools/Lighters/build-maya2023/Debug/lightsurgeon.exe" "pixel" "D:/Projects/Develop/Tools/Lighters/tests/fixtures/studio.json" "960" "540")
  set_tests_properties(lightsurgeon_cli_pixel PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;38;add_test;D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(lightsurgeon_cli_pixel "D:/Projects/Develop/Tools/Lighters/build-maya2023/Release/lightsurgeon.exe" "pixel" "D:/Projects/Develop/Tools/Lighters/tests/fixtures/studio.json" "960" "540")
  set_tests_properties(lightsurgeon_cli_pixel PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;38;add_test;D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(lightsurgeon_cli_pixel "D:/Projects/Develop/Tools/Lighters/build-maya2023/MinSizeRel/lightsurgeon.exe" "pixel" "D:/Projects/Develop/Tools/Lighters/tests/fixtures/studio.json" "960" "540")
  set_tests_properties(lightsurgeon_cli_pixel PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;38;add_test;D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(lightsurgeon_cli_pixel "D:/Projects/Develop/Tools/Lighters/build-maya2023/RelWithDebInfo/lightsurgeon.exe" "pixel" "D:/Projects/Develop/Tools/Lighters/tests/fixtures/studio.json" "960" "540")
  set_tests_properties(lightsurgeon_cli_pixel PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;38;add_test;D:/Projects/Develop/Tools/Lighters/CMakeLists.txt;0;")
else()
  add_test(lightsurgeon_cli_pixel NOT_AVAILABLE)
endif()
