# Find Autodesk Maya headers and libraries.
# Inputs: MAYA_LOCATION, Maya_DIR, or MAYA_VERSION (default 2024)
# Outputs: Maya::Maya imported target, MAYA_FOUND, MAYA_PLUGIN_SUFFIX

set(MAYA_FOUND FALSE)

set(_maya_version "2024")
if(DEFINED MAYA_VERSION)
    set(_maya_version "${MAYA_VERSION}")
endif()

if(NOT MAYA_LOCATION)
    if(WIN32)
        set(_maya_guess "C:/Program Files/Autodesk/Maya${_maya_version}")
    elseif(APPLE)
        set(_maya_guess "/Applications/Autodesk/maya${_maya_version}/Maya.app/Contents")
    else()
        set(_maya_guess "/usr/autodesk/maya${_maya_version}")
    endif()
    if(EXISTS "${_maya_guess}")
        set(MAYA_LOCATION "${_maya_guess}")
    endif()
endif()

if(MAYA_LOCATION)
    set(MAYA_INCLUDE_DIR "${MAYA_LOCATION}/include")
    if(WIN32)
        set(MAYA_LIBRARY_DIR "${MAYA_LOCATION}/lib")
        set(MAYA_PLUGIN_SUFFIX ".mll")
        set(_maya_libs Foundation OpenMaya OpenMayaAnim OpenMayaFX OpenMayaRender OpenMayaUI)
    elseif(APPLE)
        set(MAYA_LIBRARY_DIR "${MAYA_LOCATION}/MacOS")
        set(MAYA_PLUGIN_SUFFIX ".bundle")
        set(_maya_libs Foundation OpenMaya OpenMayaAnim OpenMayaFX OpenMayaRender OpenMayaUI)
    else()
        set(MAYA_LIBRARY_DIR "${MAYA_LOCATION}/lib")
        set(MAYA_PLUGIN_SUFFIX ".so")
        set(_maya_libs Foundation OpenMaya OpenMayaAnim OpenMayaFX OpenMayaRender OpenMayaUI)
    endif()

    if(EXISTS "${MAYA_INCLUDE_DIR}/maya/MFnPlugin.h")
        set(MAYA_FOUND TRUE)
        add_library(Maya::Maya INTERFACE IMPORTED)
        target_include_directories(Maya::Maya INTERFACE "${MAYA_INCLUDE_DIR}")
        foreach(_lib ${_maya_libs})
            find_library(MAYA_${_lib}_LIBRARY ${_lib} PATHS "${MAYA_LIBRARY_DIR}" NO_DEFAULT_PATH)
            if(MAYA_${_lib}_LIBRARY)
                target_link_libraries(Maya::Maya INTERFACE "${MAYA_${_lib}_LIBRARY}")
            endif()
        endforeach()
        target_compile_definitions(Maya::Maya INTERFACE REQUIRE_IOSTREAM _BOOL)
        if(WIN32)
            target_compile_definitions(Maya::Maya INTERFACE NT_PLUGIN _CRT_SECURE_NO_WARNINGS)
        elseif(APPLE)
            target_compile_definitions(Maya::Maya INTERFACE OSMac_ MAC_PLUGIN)
        else()
            target_compile_definitions(Maya::Maya INTERFACE LINUX)
        endif()
    endif()
endif()

if(NOT MAYA_FOUND)
    set(MAYA_FOUND FALSE)
endif()
